"use client";

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { CourseProvider } from "./components/context/CourseContext";
import { UserProvider } from "./components/context/CartContext";
import { TopBanner } from "./components/TopBanner";
import { Navigation } from "./components/Navigation";
import Footer from "./components/Footer";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Br Collins New",
//   description: "Generated by create next app",
// };

const queryClient = new QueryClient();

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <QueryClientProvider client={queryClient}>
      <CourseProvider>
        <UserProvider>
          <html lang="en">
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
              <main className="flex overflow-hidden flex-col bg-white">
                <TopBanner />
                <Navigation />
                {children}
                <Footer />
              </main>
            </body>
          </html>
        </UserProvider>
      </CourseProvider>
    </QueryClientProvider>
  );
}
